export const SHEET_1 = [
  {
    'TỔNG KẾT CUỐI KHÓA': 'Lớp',
    __EMPTY: 'PreS10.03',
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 'Chuyển tiếp giai đoạn',
    'Tăng cường hỗ trợ học thuật': 'Dưới chuẩn:\nPRES, S: < 70\nTC, MTC: <60',
  },
  { 'TỔNG KẾT CUỐI KHÓA': 'Giáo viên', __EMPTY: 'Vũ Hải Dương' },
  { 'TỔNG KẾT CUỐI KHÓA': 'Cơ sở', __EMPTY: 'Trần Quốc Hoàn' },
  { 'TỔNG KẾT CUỐI KHÓA': 'AC phụ trách', __EMPTY: 'Trần Thùy Anh' },
  { 'TỔNG KẾT CUỐI KHÓA': 'Ngày khai giảng', __EMPTY: 44927 },
  { 'TỔNG KẾT CUỐI KHÓA': 'Ngày kết thúc', __EMPTY: 45005 },
  {
    'TỔNG KẾT CUỐI KHÓA':
      'GV lưu ý:\n1. Điền ngày kiểm tra và nhắc nhở các học viên nghỉ thu xếp kiểm tra bù trong vòng 1 TUẦN kể từ ngày lớp kiểm tra. PĐT sẽ ghi nhận 0đ nếu học viên thiếu điểm\n2. Cột TÊN vui lòng không chỉnh sửa. Nếu có học viên mới, giáo viên điền thêm phía dưới. Nếu có học viên ngừng học, giáo viên gạch ngang (Alt + Shift + 5) dòng của học viên đó.',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 'STT',
    __EMPTY: 'Tên HV',
    __EMPTY_1: 'Mini Test (5%/bài)',
    __EMPTY_4: 'Midterm Test (30%)',
    __EMPTY_11: 'Final Test (50%)',
    __EMPTY_18: 'Trung bình toàn khóa\n100',
    __EMPTY_19: 'CHUYÊN CẦN',
    __EMPTY_23: 'Nhận xét của Giáo viên',
    __EMPTY_26: 'Đánh giá cuối khóa (auto)',
  },
  {
    __EMPTY_1: 1,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 2,
    __EMPTY_2: 3,
    'Tăng cường hỗ trợ học thuật': 4,
    __EMPTY_3: 'Trung bình',
    __EMPTY_4: 'Listening \n20',
    __EMPTY_5: 'Vocabulary\n15',
    __EMPTY_6: 'Grammar\n15',
    __EMPTY_7: 'Reading \n25',
    __EMPTY_8: 'Writing \n25',
    __EMPTY_9: 'TỔNG\n100',
    __EMPTY_10: 'Nhận xét của GV',
    __EMPTY_11: 'Listening \n20',
    __EMPTY_12: 'Vocab\n20',
    __EMPTY_13: 'Grammar\n10',
    __EMPTY_14: 'Reading \n10',
    __EMPTY_15: 'Writing \n15',
    __EMPTY_16: 'Speaking\n25',
    __EMPTY_17: 'TỔNG\n100',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 'Ngày thi',
    __EMPTY_1: 'DD/MM',
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 'DD/MM',
    __EMPTY_2: 'DD/MM',
    'Tăng cường hỗ trợ học thuật': 'DD/MM',
    __EMPTY_4: 44944,
    __EMPTY_11: 45005,
    __EMPTY_19: 'Số buổi nghỉ học',
    __EMPTY_20: 'Số buổi \nđi học',
    __EMPTY_21: 'Tỉ lệ đi học',
    __EMPTY_22: 'BTVN',
    __EMPTY_23: 'Điểm mạnh',
    __EMPTY_24: 'Điểm cần cải thiện',
    __EMPTY_25: 'Gợi ý chi tiết',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 1,
    __EMPTY: 'Hoàng Hồng Nhung',
    __EMPTY_1: 60,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 70,
    __EMPTY_2: 80,
    'Tăng cường hỗ trợ học thuật': 90,
    __EMPTY_3: 75,
    __EMPTY_4: 10,
    __EMPTY_5: 10,
    __EMPTY_6: 15,
    __EMPTY_7: 20,
    __EMPTY_8: 20,
    __EMPTY_9: 75,
    __EMPTY_10:
      'Bạn có thể nghe và trả lời các câu hỏi đơn giản. Có khả năng ghi nhớ ngữ pháp tốt. Tuy nhiên cần luyện tập thêm kỹ năng Listening. ',
    __EMPTY_11: 15,
    __EMPTY_12: 15,
    __EMPTY_13: 7,
    __EMPTY_14: 8,
    __EMPTY_15: 10,
    __EMPTY_16: 15,
    __EMPTY_17: 70,
    __EMPTY_18: 72.5,
    __EMPTY_19: 1,
    __EMPTY_20: 23,
    __EMPTY_21: 0.9583333333,
    __EMPTY_22: 0.9,
    __EMPTY_23:
      'Bạn đã nắm được hơn 60% nội dung kiến thức có trong khóa học, bạn có thể hiểu và sử dụng các từ vựng ngắn trong các cuộc hội thoại về chủ đề đơn giản. \n',
    __EMPTY_24:
      'Tuy nhiên bạn còn mắc một số lỗi khi sử dụng ngôn ngữ như lựa chọn từ chưa phù hợp với văn cảnh, hiểu nhầm ý. ',
    __EMPTY_25:
      'Bạn cần luyện tập thêm khả năng Speaking của mình, Jaxtina gợi ý cho bạn một số cách luyện tập sau:\n1. Học qua shadowing: Bạn hãy xem một video ngắn về một chủ đề yêu thích và nhại lại đúng ngữ điệu và cách nói trong video \n2. Hãy dành thời gian luyện tập hàng ngày: Bạn hãy tập đứng trước gương và thử nói chuyện với chính mình.',
    __EMPTY_26: 'Good',
    __EMPTY_27: 'Chuyển tiếp giai đoạn',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 2,
    __EMPTY: 'Nguyễn Thị Phương Thảo',
    __EMPTY_1: 100,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 100,
    __EMPTY_2: 96,
    'Tăng cường hỗ trợ học thuật': 96,
    __EMPTY_3: 98,
    __EMPTY_4: 12,
    __EMPTY_5: 15,
    __EMPTY_6: 15,
    __EMPTY_7: 10,
    __EMPTY_8: 10,
    __EMPTY_9: 62,
    __EMPTY_10:
      'Bạn có khả năng học tập tốt, cần cải thiện thêm kỹ năng Reading và Wrting.',
    __EMPTY_11: 12,
    __EMPTY_12: 19,
    __EMPTY_13: 8,
    __EMPTY_14: 9,
    __EMPTY_15: 8,
    __EMPTY_16: 20,
    __EMPTY_17: 76,
    __EMPTY_18: 76.2,
    __EMPTY_19: 0,
    __EMPTY_20: 24,
    __EMPTY_21: 1,
    __EMPTY_22: 0.7,
    __EMPTY_23:
      'Bạn đã nắm được tương đối tốt nội dung kiến thức có trong khóa học, có ý thức học tốt, chủ động ôn tập xin thêm tài liệu bổ trợ, kĩ năng nói đã cải thiện nhanh chóng,\n\n\n',
    __EMPTY_24:
      'Tuy nhiên bạn vẫn còn mắc một số ít lỗi khi sử dụng ngôn ngữ, có thể hiểu nhầm ý trong những văn cảnh không quen thuộc. \r',
    __EMPTY_25:
      'Bạn cần luyện tập thêm khả năng Listening và Writing của mình, Jaxtina gợi ý cho bạn một số cách luyện tập sau:\n1. Listening: Hãy nghe lại nhiều lần transcript trên lớp để nắm được trọn vẹn nội dung của bài học hoặc bạn có thể áp dụng phương pháp Dictation (Nghe chép chính tả) để luyện tập nghe và chép lại tất cả những gì mình nghe được. Luyện tập thường xuyên sẽ giúp kỹ năng Nghe của bạn được cải thiện đáng kể đấy.\n2. Writing: Hãy luyện tập viết câu ngắn chính xác về cấu trúc và từ vựng. Sau đó, thử viết về các chủ đề quen thuộc trong cuộc sống. Các giáo viên tại Jaxtina có thể hỗ trợ bạn kiểm tra và chữa bài viết nếu bạn thật sự muốn cải thiện kỹ năng ngôn ngữ của mình.',
    __EMPTY_26: 'Good',
    __EMPTY_27: 'Chuyển tiếp giai đoạn',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 3,
    __EMPTY: 'Nguyễn Thu Trang',
    __EMPTY_1: 65,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 0,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 92,
    __EMPTY_3: 39.25,
    __EMPTY_4: 16,
    __EMPTY_5: 10,
    __EMPTY_6: 14,
    __EMPTY_7: 10,
    __EMPTY_8: 13,
    __EMPTY_9: 63,
    __EMPTY_10:
      'Bạn có sự tập trung trong giơ học, tuy nhiên cần đi học đầy đủ và luyện tập cả 4 kỹ năng thường xuyên hơn',
    __EMPTY_11: 12,
    __EMPTY_12: 13,
    __EMPTY_13: 5,
    __EMPTY_14: 6,
    __EMPTY_15: 2,
    __EMPTY_16: 7,
    __EMPTY_17: 45,
    __EMPTY_18: 49.25,
    __EMPTY_19: 3,
    __EMPTY_20: 21,
    __EMPTY_21: 0.875,
    __EMPTY_22: 0.8,
    __EMPTY_23:
      'Bạn có sự cố gắng để cải thiện khả năng ngôn ngữ của mình, có thái độ tốt trong quá trình học tập.\n\n',
    __EMPTY_24:
      'Tuy nhiên, hãy xem lại quá trình học vừa rồi, bạn có nghỉ nhiều, có chuẩn bị bài trước khi đến lớp như yêu cầu khóa học đề ra không? \n\n',
    __EMPTY_25:
      'Bạn cần chủ động xem lại tất cả từ vựng và hệ thống ngữ pháp đã được giới thiệu trong khóa học. \n\n',
    __EMPTY_26: 'Needs Improvement',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 4,
    __EMPTY: 'Ngô Văn Lân',
    __EMPTY_1: 100,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 94,
    __EMPTY_2: 74,
    'Tăng cường hỗ trợ học thuật': 100,
    __EMPTY_3: 92,
    __EMPTY_4: 18,
    __EMPTY_5: 14,
    __EMPTY_6: 10,
    __EMPTY_7: 14,
    __EMPTY_8: 12,
    __EMPTY_9: 68,
    __EMPTY_10:
      'Bạn có khả năng Nghe tốt, tuy nhiên việc ghi nhớ các Cấu trúc ngữ pháp còn hạn chế. cần luyện tập thêm.',
    __EMPTY_11: 12,
    __EMPTY_12: 13,
    __EMPTY_13: 1,
    __EMPTY_14: 8,
    __EMPTY_15: 7,
    __EMPTY_16: 13,
    __EMPTY_17: 54,
    __EMPTY_18: 65.8,
    __EMPTY_19: 0,
    __EMPTY_20: 24,
    __EMPTY_21: 1,
    __EMPTY_22: 1,
    __EMPTY_23:
      'Bạn đã nắm được từ vựng và các hiện tượng ngữ pháp cơ bản, có thái độ tích cực học hỏi trong giờ học. Bạn đã cải thiện rất tốt khả năng phát âm của mình.\n\n',
    __EMPTY_24: 'Tuy nhiên, bạn vẫn hay mắc lỗi khi sử dụng ngôn ngữ.  \n\n',
    __EMPTY_25:
      'Bạn cần cố gắng nhiều hơn nữa để có thể truyền tải và sử dụng được tiếng Anh.',
    __EMPTY_26: 'Fair',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 5,
    __EMPTY: 'Trịnh Vân Sơn',
    __EMPTY_1: 69,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 97,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 92,
    __EMPTY_3: 64.5,
    __EMPTY_4: 7,
    __EMPTY_5: 13,
    __EMPTY_6: 13,
    __EMPTY_7: 10,
    __EMPTY_8: 4,
    __EMPTY_9: 47,
    __EMPTY_10:
      'Bạn ghi nhớ Từ vựng và Ngữ pháp tốt, tuy nhiên để áp dụng vào việc Nghe, Nói, Viết bạn cần luyện tập thêm.',
    __EMPTY_11: 14,
    __EMPTY_12: 17,
    __EMPTY_13: 8,
    __EMPTY_14: 8,
    __EMPTY_15: 10,
    __EMPTY_16: 13,
    __EMPTY_17: 70,
    __EMPTY_18: 62,
    __EMPTY_19: 2,
    __EMPTY_20: 22,
    __EMPTY_21: 0.9166666667,
    __EMPTY_22: 0.9,
    __EMPTY_23:
      'Bạn đã nắm được hơn 60% nội dung kiến thức có trong khóa học, có khả năng tiếp thu ngôn ngữ tốt. Bạn đã nói được trọn vẹn cả câu khi muốn diễn đạt ý tưởng của mình.\n\n',
    __EMPTY_24:
      'Tuy nhiên vẫn còn mắc một số lỗi khi sử dụng ngôn ngữ như lựa chọn từ chưa phù hợp với văn cảnh, hiểu nhầm ý. \n\n\n',
    __EMPTY_25:
      'Bạn cần luyện tập thêm khả năng Speaking của mình, Jaxtina gợi ý cho bạn một số cách luyện tập sau:\n1. Học qua shadowing: Bạn hãy xem một video ngắn về một chủ đề yêu thích và nhại lại đúng ngữ điệu và cách nói trong video \n2. Hãy dành thời gian luyện tập hàng ngày: Bạn hãy tập đứng trước gương và thử nói chuyện với chính mình.',
    __EMPTY_26: 'Good',
    __EMPTY_27: 'Chuyển tiếp giai đoạn',
  },
  {
    __EMPTY_1: 0,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 0,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 0,
    __EMPTY_3: 0,
    __EMPTY_4: 0,
    __EMPTY_5: 0,
    __EMPTY_6: 0,
    __EMPTY_7: 0,
    __EMPTY_8: 0,
    __EMPTY_9: 0,
    __EMPTY_11: 0,
    __EMPTY_12: 0,
    __EMPTY_13: 0,
    __EMPTY_14: 0,
    __EMPTY_15: 0,
    __EMPTY_16: 0,
    __EMPTY_17: 0,
    __EMPTY_18: 0,
    __EMPTY_19: 2,
    __EMPTY_20: 22,
    __EMPTY_21: 0.9166666667,
    __EMPTY_26: 'Needs Improvement',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 7,
    __EMPTY_1: 0,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 0,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 0,
    __EMPTY_3: 0,
    __EMPTY_4: 0,
    __EMPTY_5: 0,
    __EMPTY_6: 0,
    __EMPTY_7: 0,
    __EMPTY_8: 0,
    __EMPTY_9: 0,
    __EMPTY_11: 0,
    __EMPTY_12: 0,
    __EMPTY_13: 0,
    __EMPTY_14: 0,
    __EMPTY_15: 0,
    __EMPTY_16: 0,
    __EMPTY_17: 0,
    __EMPTY_18: 0,
    __EMPTY_19: 0,
    __EMPTY_21: '#DIV/0!',
    __EMPTY_26: 'Needs Improvement',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 8,
    __EMPTY_1: 0,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 0,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 0,
    __EMPTY_3: 0,
    __EMPTY_4: 0,
    __EMPTY_5: 0,
    __EMPTY_6: 0,
    __EMPTY_7: 0,
    __EMPTY_8: 0,
    __EMPTY_9: 0,
    __EMPTY_11: 0,
    __EMPTY_12: 0,
    __EMPTY_13: 0,
    __EMPTY_14: 0,
    __EMPTY_15: 0,
    __EMPTY_16: 0,
    __EMPTY_17: 0,
    __EMPTY_18: 0,
    __EMPTY_19: 0,
    __EMPTY_21: '#DIV/0!',
    __EMPTY_26: 'Needs Improvement',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 9,
    __EMPTY_1: 0,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 0,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 0,
    __EMPTY_3: 0,
    __EMPTY_4: 0,
    __EMPTY_5: 0,
    __EMPTY_6: 0,
    __EMPTY_7: 0,
    __EMPTY_8: 0,
    __EMPTY_9: 0,
    __EMPTY_11: 0,
    __EMPTY_12: 0,
    __EMPTY_13: 0,
    __EMPTY_14: 0,
    __EMPTY_15: 0,
    __EMPTY_16: 0,
    __EMPTY_17: 0,
    __EMPTY_18: 0,
    __EMPTY_19: 0,
    __EMPTY_21: '#DIV/0!',
    __EMPTY_26: 'Needs Improvement',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 10,
    __EMPTY_1: 0,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 0,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 0,
    __EMPTY_3: 0,
    __EMPTY_4: 0,
    __EMPTY_5: 0,
    __EMPTY_6: 0,
    __EMPTY_7: 0,
    __EMPTY_8: 0,
    __EMPTY_9: 0,
    __EMPTY_11: 0,
    __EMPTY_12: 0,
    __EMPTY_13: 0,
    __EMPTY_14: 0,
    __EMPTY_15: 0,
    __EMPTY_16: 0,
    __EMPTY_17: 0,
    __EMPTY_18: 0,
    __EMPTY_19: 0,
    __EMPTY_21: '#DIV/0!',
    __EMPTY_26: 'Needs Improvement',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 11,
    __EMPTY_1: 0,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 0,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 0,
    __EMPTY_3: 0,
    __EMPTY_4: 0,
    __EMPTY_5: 0,
    __EMPTY_6: 0,
    __EMPTY_7: 0,
    __EMPTY_8: 0,
    __EMPTY_9: 0,
    __EMPTY_11: 0,
    __EMPTY_12: 0,
    __EMPTY_13: 0,
    __EMPTY_14: 0,
    __EMPTY_15: 0,
    __EMPTY_16: 0,
    __EMPTY_17: 0,
    __EMPTY_18: 0,
    __EMPTY_19: 0,
    __EMPTY_21: '#DIV/0!',
    __EMPTY_26: 'Needs Improvement',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 12,
    __EMPTY_1: 0,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 0,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 0,
    __EMPTY_3: 0,
    __EMPTY_4: 0,
    __EMPTY_5: 0,
    __EMPTY_6: 0,
    __EMPTY_7: 0,
    __EMPTY_8: 0,
    __EMPTY_9: 0,
    __EMPTY_11: 0,
    __EMPTY_12: 0,
    __EMPTY_13: 0,
    __EMPTY_14: 0,
    __EMPTY_15: 0,
    __EMPTY_16: 0,
    __EMPTY_17: 0,
    __EMPTY_18: 0,
    __EMPTY_19: 0,
    __EMPTY_21: '#DIV/0!',
    __EMPTY_26: 'Needs Improvement',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 13,
    __EMPTY_1: 0,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 0,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 0,
    __EMPTY_3: 0,
    __EMPTY_4: 0,
    __EMPTY_5: 0,
    __EMPTY_6: 0,
    __EMPTY_7: 0,
    __EMPTY_8: 0,
    __EMPTY_9: 0,
    __EMPTY_11: 0,
    __EMPTY_12: 0,
    __EMPTY_13: 0,
    __EMPTY_14: 0,
    __EMPTY_15: 0,
    __EMPTY_16: 0,
    __EMPTY_17: 0,
    __EMPTY_18: 0,
    __EMPTY_19: 0,
    __EMPTY_21: '#DIV/0!',
    __EMPTY_26: 'Needs Improvement',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 14,
    __EMPTY_1: 0,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 0,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 0,
    __EMPTY_3: 0,
    __EMPTY_4: 0,
    __EMPTY_5: 0,
    __EMPTY_6: 0,
    __EMPTY_7: 0,
    __EMPTY_8: 0,
    __EMPTY_9: 0,
    __EMPTY_11: 0,
    __EMPTY_12: 0,
    __EMPTY_13: 0,
    __EMPTY_14: 0,
    __EMPTY_15: 0,
    __EMPTY_16: 0,
    __EMPTY_17: 0,
    __EMPTY_18: 0,
    __EMPTY_19: 0,
    __EMPTY_21: '#DIV/0!',
    __EMPTY_26: 'Needs Improvement',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 15,
    __EMPTY_1: 0,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 0,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 0,
    __EMPTY_3: 0,
    __EMPTY_4: 0,
    __EMPTY_5: 0,
    __EMPTY_6: 0,
    __EMPTY_7: 0,
    __EMPTY_8: 0,
    __EMPTY_9: 0,
    __EMPTY_11: 0,
    __EMPTY_12: 0,
    __EMPTY_13: 0,
    __EMPTY_14: 0,
    __EMPTY_15: 0,
    __EMPTY_16: 0,
    __EMPTY_17: 0,
    __EMPTY_18: 0,
    __EMPTY_19: 0,
    __EMPTY_21: '#DIV/0!',
    __EMPTY_26: 'Needs Improvement',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 16,
    __EMPTY_1: 0,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 0,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 0,
    __EMPTY_3: 0,
    __EMPTY_4: 0,
    __EMPTY_5: 0,
    __EMPTY_6: 0,
    __EMPTY_7: 0,
    __EMPTY_8: 0,
    __EMPTY_9: 0,
    __EMPTY_11: 0,
    __EMPTY_12: 0,
    __EMPTY_13: 0,
    __EMPTY_14: 0,
    __EMPTY_15: 0,
    __EMPTY_16: 0,
    __EMPTY_17: 0,
    __EMPTY_18: 0,
    __EMPTY_19: 0,
    __EMPTY_21: '#DIV/0!',
    __EMPTY_26: 'Needs Improvement',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 17,
    __EMPTY_1: 0,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 0,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 0,
    __EMPTY_3: 0,
    __EMPTY_4: 0,
    __EMPTY_5: 0,
    __EMPTY_6: 0,
    __EMPTY_7: 0,
    __EMPTY_8: 0,
    __EMPTY_9: 0,
    __EMPTY_11: 0,
    __EMPTY_12: 0,
    __EMPTY_13: 0,
    __EMPTY_14: 0,
    __EMPTY_15: 0,
    __EMPTY_16: 0,
    __EMPTY_17: 0,
    __EMPTY_18: 0,
    __EMPTY_19: '',
    __EMPTY_21: '',
    __EMPTY_26: 'Needs Improvement',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 18,
    __EMPTY_1: 0,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 0,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 0,
    __EMPTY_3: 0,
    __EMPTY_4: 0,
    __EMPTY_5: 0,
    __EMPTY_6: 0,
    __EMPTY_7: 0,
    __EMPTY_8: 0,
    __EMPTY_9: 0,
    __EMPTY_11: 0,
    __EMPTY_12: 0,
    __EMPTY_13: 0,
    __EMPTY_14: 0,
    __EMPTY_15: 0,
    __EMPTY_16: 0,
    __EMPTY_17: 0,
    __EMPTY_18: 0,
    __EMPTY_19: '',
    __EMPTY_21: '',
    __EMPTY_26: 'Needs Improvement',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 19,
    __EMPTY_1: 0,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 0,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 0,
    __EMPTY_3: 0,
    __EMPTY_4: 0,
    __EMPTY_5: 0,
    __EMPTY_6: 0,
    __EMPTY_7: 0,
    __EMPTY_8: 0,
    __EMPTY_9: 0,
    __EMPTY_11: 0,
    __EMPTY_12: 0,
    __EMPTY_13: 0,
    __EMPTY_14: 0,
    __EMPTY_15: 0,
    __EMPTY_16: 0,
    __EMPTY_17: 0,
    __EMPTY_18: 0,
    __EMPTY_19: '',
    __EMPTY_21: '',
    __EMPTY_26: 'Needs Improvement',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 20,
    __EMPTY_1: 0,
    'Đạt đầu ra: \nPRES, S: >= 70\nTC, MTC: >=60': 0,
    __EMPTY_2: 0,
    'Tăng cường hỗ trợ học thuật': 0,
    __EMPTY_3: 0,
    __EMPTY_4: 0,
    __EMPTY_5: 0,
    __EMPTY_6: 0,
    __EMPTY_7: 0,
    __EMPTY_8: 0,
    __EMPTY_9: 0,
    __EMPTY_11: 0,
    __EMPTY_12: 0,
    __EMPTY_13: 0,
    __EMPTY_14: 0,
    __EMPTY_15: 0,
    __EMPTY_16: 0,
    __EMPTY_17: 0,
    __EMPTY_18: 0,
    __EMPTY_19: '',
    __EMPTY_21: '',
    __EMPTY_26: 'Needs Improvement',
    __EMPTY_27: 'Tăng cường hỗ trợ học thuật',
  },
  {
    __EMPTY: 'Tổng',
    __EMPTY_8: 'Đạt',
    __EMPTY_9: 4,
    __EMPTY_16: 'Đi thi',
    __EMPTY_17: '#REF!',
    __EMPTY_19: '',
    __EMPTY_21: '',
    __EMPTY_23: 'Đạt',
    __EMPTY_26: 0,
  },
  {
    'TỔNG KẾT CUỐI KHÓA': 'Tỉ lệ đạt chuẩn đầu ra khóa học',
    __EMPTY_1: '#REF!',
  },
  { 'TỔNG KẾT CUỐI KHÓA': 'Số lượng đạt điểm 70 - 100', __EMPTY_1: 2 },
  { 'TỔNG KẾT CUỐI KHÓA': 'Số lượng đạt điểm 80 - 100', __EMPTY_1: 0 },
  { 'TỔNG KẾT CUỐI KHÓA': 'Số lượng đạt điểm 85 - 100', __EMPTY_1: 0 },
];
